name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # 1. 安装并缓存 vcpkg
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    # 2. 安装 vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout 4fcf123fe53c63db265b5841a5aeff06cec375a1
        ./bootstrap-vcpkg.sh
        
    # 3. 安装依赖
    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install --triplet x64-linux

    # 4. 配置 CMake（使用 vcpkg 工具链）
    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
      
    # 5. 构建
    - name: Build
      run: cmake --build build
