name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libunwind-dev \
          libboost-all-dev \
          libssl-dev \
          libgflags-dev \
          libdouble-conversion-dev \
          libevent-dev \
          libfmt-dev \
          qt6-base-dev \
          libgoogle-glog-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build
